---
title: "ChurnPrediction.Tidymodels"
author: "Isioma Mabatah"
date: "4/22/2021"
output: 
  html_document:
    theme: lumen
    toc: true
    toc_float: true
    code_folding: hide
---

# Libraries

```{r lib}
library(tidymodels)
library(workflowsets)
library(doParallel)
```

# Data

```{r data}
# Raw Data
hr_raw <- readr::read_csv("HR-Employee-Attrition.csv")

# Clean data: Factors
hr_clean <- hr_raw %>%
  mutate(Attrition = factor(ifelse(Attrition == "Yes", 1,0),
                            labels =  c("Stayed", "Churn")),
         BusinessTravel = factor(BusinessTravel,
                                 levels = c("Non-Travel","Travel_Rarely","Travel_Frequently")),
         Department = factor(Department),
         EducationField = factor(EducationField),
         Gender = factor(Gender),
         JobLevel = factor(JobLevel),
         JobRole = factor(JobRole),
         MaritalStatus = factor(MaritalStatus),
         Over18 = factor(Over18),
         OverTime = factor(OverTime),
         StockOptionLevel = factor(StockOptionLevel),
         Education = factor(Education,
                            levels = c(1:5), 
                            labels = c("Below College","College","Bachelor","Master","Doctor")),
         EnvironmentSatisfaction = factor(EnvironmentSatisfaction,
                                          levels = c(1:4),
                                          labels = c("Low","Medium","High","Very High")),
         JobInvolvement = factor(JobInvolvement,
                                 levels = c(1:4),
                                 labels = c("Low","Medium","High","Very High")),
         JobSatisfaction = factor(JobSatisfaction,
                                  levels = c(1:4),
                                  labels = c("Low","Medium","High","Very High")),
         PerformanceRating = factor(PerformanceRating,
                                    levels = c(1:4),
                                    labels = c("Low","Good","Excellent","Outstanding")),
         RelationshipSatisfaction = factor(RelationshipSatisfaction,
                                           levels = c(1:4),
                                           labels = c("Low","Medium","High","Very High")),
         WorkLifeBalance = factor(WorkLifeBalance,
                                  levels = c(1:4),
                                  labels = c("Bad","Good","Better","Best")))

hr_clean %>% glimpse()
```


# EDA (Simple)

```{r eda, fig.align='center', fig.height=8, fig.width=8}
# Summary
hr_clean %>% skimr::skim()
# - Zero Variance: Over18 | EmployeeCount | Standard Hours

# Correlation Matrix
hr_clean %>% 
  select_if(is.numeric) %>% select(-EmployeeCount, -StandardHours) %>% 
  cor() %>% 
  ggcorrplot::ggcorrplot(type = "upper", lab = TRUE, lab_size = 2)
```

# Modeling

## Data Split

```{r Model_Split}
# Split
set.seed(0923)
hr_split <- hr_clean %>% initial_split(prop = 0.6, strata = Attrition)
hr_train <- training(hr_split)
hr_test <- testing(hr_split)
# - validation st
hr_5fold <- vfold_cv(hr_train, v = 5, strata = Attrition)

```

## Preprocess

```{r Model_Prep}
# Advanced Recipe
hr_adv_rec <- 
  recipe(Attrition ~ ., data = hr_train) %>% 
  update_role(EmployeeNumber, new_role = "ID") %>% 
  step_rm(Over18) %>% 
  step_zv(all_numeric()) %>% 
  step_normalize(all_numeric()) %>% 
  step_corr(all_numeric(), threshold = 0.75) %>% 
  step_dummy(all_nominal(), -all_outcomes())
# -  data
hr_adv_rec %>% 
  prep() %>% juice() %>% 
  glimpse()

# Simple Recipe
hr_simple_rec <- 
  recipe(Attrition ~ ., data = hr_train) %>% 
  update_role(EmployeeNumber, new_role = "ID") %>% 
  step_rm(Over18) %>% 
  step_dummy(all_nominal(), -all_outcomes())
# - data
hr_simple_rec %>% 
  prep() %>% juice() %>% 
  glimpse()

# Undersample
# Adv
hr_adv_rec_DOWN <- 
  hr_adv_rec %>% 
  step_downsample(Attrition)
# - data
hr_adv_rec_DOWN %>% 
  prep() %>% juice() %>% 
  glimpse()
# Simple
hr_simple_rec_DOWN <- 
  hr_simple_rec %>% 
  step_downsample(Attrition)

# Oversample
# Adv
hr_adv_rec_UP <- 
  hr_adv_rec %>% 
  step_upsample(Attrition)
# - data
hr_adv_rec_UP %>% 
  prep() %>% juice() %>% 
  glimpse()
# Simple
hr_simple_rec_UP <- 
  hr_simple_rec %>% 
  step_upsample(Attrition)
```

```{r Model_Ctrl}
# Parallel Processing
cl_3 <- makeCluster(4)

# Metric
hr_metrics <- metric_set(roc_auc, sens, spec, recall, precision)

# Control
hr_ctrl <- 
  control_resamples(verbose = TRUE,
                    allow_par = TRUE,
                    save_pred = TRUE,
                    event_level = "second")
```


## Fit [TABS] {.tabset .tabset-fade}

```{r start_Parallel}
# Register Parallel Computing
registerDoParallel(cl_3)
```

### Lasso Regression

```{r spec_Lasso}
# Spec
hr_log_spec <- 
  logistic_reg(
    penalty = tune(),
    mixture = 1
  ) %>% 
  set_engine("glmnet") %>% 
  set_mode("classification")

# Workflow
hr_log_wflow <- 
  workflow() %>% 
  add_recipe(hr_adv_rec) %>% 
  add_model(hr_log_spec)

# Hyperparameters
hr_log_grid <- 
  hr_log_spec %>% 
  parameters() %>% 
  grid_regular(levels = 10, orginal = TRUE)
```

```{r fit_Lasso}
# Fit
hr_log_tune <- 
  hr_log_wflow %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_log_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visual
hr_log_tune %>% 
  autoplot() + 
  theme_bw()
# - best
hr_log_tune %>% select_best("sens")
```

```{r under_Lasso}
# Fit
hr_log_tune_DOWN <- 
  hr_log_wflow %>% 
  update_recipe(hr_adv_rec_DOWN) %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_log_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visual
hr_log_tune_DOWN %>% 
  autoplot() + 
  theme_bw()
# - best
hr_log_tune_DOWN %>% select_best("sens")
```

```{r over_Lasso}
# Fit
hr_log_tune_UP <- 
  hr_log_wflow %>% 
  update_recipe(hr_adv_rec_UP) %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_log_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - Visual
hr_log_tune_UP %>% 
  autoplot() + 
  theme_bw()
# - Best
hr_log_tune_UP %>% select_best("sens")
```

### Support Vector Machine

```{r spec_SVM}
# Spec
hr_svm_spec <- 
  svm_rbf(
    cost = tune(),
    rbf_sigma = tune()
  ) %>% 
  set_engine("kernlab") %>% 
  set_mode("classification")

# Workflow
hr_svm_wflow <- 
  workflow() %>% 
  add_recipe(hr_adv_rec) %>% 
  add_model(hr_svm_spec)

# Hyperparameters
hr_svm_grid <- 
  hr_svm_spec %>% 
  parameters() %>% 
  grid_latin_hypercube(size = 20, original = TRUE)
```

```{r fit_SVM}
# Fit
hr_svm_tune <- 
  hr_svm_wflow %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_svm_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visual
hr_svm_tune %>% 
  autoplot() +
  theme_bw()
# - best
hr_svm_tune %>% select_best("sens")
```

```{r under_SVM}
# Fit
hr_svm_tune_DOWN <- 
  hr_svm_wflow %>% 
  update_recipe(hr_adv_rec_DOWN) %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_svm_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visual
hr_svm_tune_DOWN %>% 
  autoplot() +
  theme_bw()
# - best
hr_svm_tune_DOWN %>% select_best("sens")
```

```{r over_SVM}
# Fit
hr_svm_tune_UP <- 
  hr_svm_wflow %>% 
  update_recipe(hr_adv_rec_UP) %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_svm_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visaul
hr_svm_tune_UP %>% 
  autoplot() +
  theme_bw()
# - best
hr_svm_tune_UP %>% select_best("sens")
```

### Random Forrest

```{r spec_RF}
# Spec
hr_rf_spec <- 
  rand_forest(
    mtry = tune(), 
    trees = 5000,
    min_n = tune()
  ) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

# Workflow
hr_rf_wflow <- 
  workflow() %>% 
  add_recipe(hr_simple_rec) %>% 
  add_model(hr_rf_spec)

# Hyperparameter
hr_rf_grid <- 
  grid_regular(
    mtry(range = c(1,35)),
    min_n(range = c(2,10)),
    levels = 5
  )
```

```{r fit_RF}
# Fit
hr_rf_tune <- 
  hr_rf_wflow %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_rf_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visual
hr_rf_tune %>% 
  autoplot() +
  theme_bw()
# - best
hr_rf_tune %>% select_best("sens")
```

```{r under_RF}
# Fit
hr_rf_tune_DOWN <-
  hr_rf_wflow %>% 
  update_recipe(hr_simple_rec_DOWN) %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_rf_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visual
hr_rf_tune_DOWN %>% 
  autoplot() + 
  theme_bw()
# - best
hr_rf_tune_DOWN %>% select_best("sens")
```

```{r over_RF}
# Fit
hr_rf_tune_UP <-
  hr_rf_wflow %>% 
  update_recipe(hr_simple_rec_UP) %>% 
  tune_grid(
    resamples = hr_5fold,
    grid = hr_rf_grid,
    metrics = hr_metrics,
    control = hr_ctrl
  )
# - visual
hr_rf_tune_UP %>% 
  autoplot() + 
  theme_bw()
# - best
hr_rf_tune_UP %>% select_best("sens")
```

## Workflow set

```{r}
workflow_Baseline <- 
  workflow_set(
    preproc = list(simple = hr_simple_rec, adv = hr_norm_corr_rec),
    models = list(Lasso = hr_log_spec, SVM = hr_svm_spec, RF = hr_rf_spec)
  )


workflow_Baseline %>% pull_workflow(id = "simple_Lasso")
option
```

```{r stop_Parallel}
# Stop Cluster
stopCluster(cl_3)
```

